language: php

php:
  - 5.4

env:
  - MONGO_VERSION=1.2.12

services: mongodb

before_script:
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - git submodule update --init
  - cp .travis/composer.json ./    
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install